# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAlHzpT177C3uNvhTjLNLDCbsGp_iv1x

#Clustering
"""

# utils/clustering.py

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

def prepare_hourly_data(df):
    """
    Mengambil rata-rata konsumsi listrik berdasarkan jam.
    """
    df = df.copy()
    df['hour'] = df['timestamp'].dt.hour
    hourly_avg = df.groupby('hour')['power_usage_watt'].mean().reset_index()
    return hourly_avg

def run_clustering(hourly_df, n_clusters=3):
    """
    Menjalankan KMeans clustering terhadap data konsumsi per jam.
    """
    scaler = StandardScaler()
    scaled = scaler.fit_transform(hourly_df[['power_usage_watt']])

    model = KMeans(n_clusters=n_clusters, random_state=42, n_init='auto')
    labels = model.fit_predict(scaled)

    hourly_df['cluster'] = labels
    return hourly_df, model, scaler