# -*- coding: utf-8 -*-
"""forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh94jvqzrF62K07wuRvDhGcCk9f93Dan

#Forecast
"""

# utils/forecast.py

import pandas as pd
from prophet import Prophet

def prepare_prophet_data(df):
    daily_total = df.groupby(df['timestamp'].dt.date)["power_usage_watt"].sum().reset_index()
    daily_total.columns = ["ds", "y"]
    return daily_total

def train_forecast_model(df, periods=7):
    prophet_df = prepare_prophet_data(df)
    model = Prophet()
    model.fit(prophet_df)
    future = model.make_future_dataframe(periods=periods)
    forecast = model.predict(future)
    return model, forecast